#!/bin/bash

if pgrep -x "gpsd" > /dev/null; then
	if sudo killall gpsd; then
	    echo "GPSD KILLED"
	else
		echo "UNEXPECTED ERROR WHILE STOPPING GPSD"
	fi
else
    echo "GPSD WAS NOT RUNNING ALREADY"
fi

if sudo gpsd /dev/ttyAMA0 -F /var/run/gpsd.sock; then
    echo "SOCKET INITIALIZED"
else
    echo "SOCKET NOT INITIALIZED!"
fi
